# Двойственная Задача
## Вариант № 10

1x1 + 1x2 <= 16
0.5x1 + 1x2 <= 12
0x1 + 1x2 <= 12
0.8x1 + 1.5x2 <= 16

Так как базисные переменные x1, x4, x5, x2 то матрица:
a1 = 1 0.5 0 0.8
a4 = 0 1 0 0
a5 = 0 0 1 0
a2 = 1 1 1 1.5

# Импорт либ

In [95]:
import numpy as np

# Первая теорема

In [96]:
def TheoremeOne():

    A = np.array([[1, 0, 0, 1],
                  [0.5, 1, 0, 1],
                  [0,   0, 1,  1],
                  [0.8, 0, 0,  1.5]])

    print("Базисная матрица:")
    print(A, "\n")



    print("Обратная матрица:")
    DminOne = np.linalg.inv(A)
    print(DminOne, '\n')

    print("y = Cb * D^-1:")
    Cb = np.array([20, 0, 0, 30])
    y = np.dot(Cb, DminOne)
    print(y, '\n')

    print("Значение при умножении A0 и y")
    A0 = np.array([16, 12, 12, 16])
    res = np.dot(y, A0)
    print(res)

TheoremeOne()

Базисная матрица:
[[1.  0.  0.  1. ]
 [0.5 1.  0.  1. ]
 [0.  0.  1.  1. ]
 [0.8 0.  0.  1.5]] 

Обратная матрица:
[[ 2.14285714  0.          0.         -1.42857143]
 [ 0.07142857  1.          0.         -0.71428571]
 [ 1.14285714  0.          1.         -1.42857143]
 [-1.14285714  0.          0.          1.42857143]] 

y = Cb * D^-1:
[ 8.57142857  0.          0.         14.28571429] 

Значение при умножении A0 и y
365.7142857142857


# Вторая теорема

система уравнений:
1y1 + 5y2 + 3y3 = 3
0.5y1 + 3y2 + 6y3 = 6
4y1 + 0y2 + 3y3 = 12

система уравнений:
1y1 + 0.5y2 + 0y3 + 0.8y4 = 20
1y1 + 1y2 + 1y3 + 1.5y4 = 30

In [97]:
RatioY = np.array([[1, 0.5, 0, 0.8],
                   [1, 1, 1, 1.5],
                   [1, 1, 1, 1],
                   [1, 1, 1, 1]])

Output = np.array([16, 12, 12, 16])
print(RatioY.shape)
print(Output.shape)

TmpRes = np.linalg.solve(RatioY, Output)
print(TmpRes)

#A0 = [3400, 1200, 3000]

#Res = np.dot(A0, TmpRes)
#print(Res)

(4, 4)
(4,)


LinAlgError: Singular matrix

# Третья теорема

In [98]:
D = [[2.14285714, 0.07142857, 1.14285714, -1.14285714],
     [0, 1, 0, 0],
     [0, 0, 1, 0],
     [-1.42857143, -0.71428571, -1.42857143, 1.42857143]]

# A = [3400, 1200, 3000]

A = [16, 12, 12, 16]

y = [ 8.57142857, 0, 0, 14.28571429]
v=[]
for i in range(len(D)):
    j = []
    jj = []
    u = []
    uu=[]
    for k in range(len(D[i])):
        if D[i][k] > 0:
            j.append(D[i][k])
            jj.append(k)
        elif D[i][k] < 0:
            u.append(D[i][k])
            uu.append(k)
            ma=0;
    if len(u) > 1:
        f=[]
        for g in range(len(u)):
            f.append((A[uu[g]]/u[g])*(-1))
            ma=max(f)
    elif len(u) == 1:
        ma=(A[uu[0]]/u[0])*(-1)
    else:
        ma=float("inf")
    if len(j) > 1:
        f=[]
        for g in range(len(j)):
            f.append((A[jj[g]]/j[g]))
            mi=max(f)
    else:
        mi=(A[jj[0]]/j[0])
    v.append(ma)
    print("Максимум в стобце "+str(i+1)+" = "+str(ma))
    print("Минимум в стобце "+str(i+1)+" = "+str(mi))
    le=A[len(A)-i-1]-mi
    if(ma==float("inf")):
        ri=float("inf")
    else:
        ri = A[len(A)-i-1] + ma
    print("ограничения в столбце "+str(i+1)+" = ("+str(le)+";"+str(ri)+")")

vliyan=0
iter=0
for z in range(len(v)):
    print("Влияние "+str(z+1)+" ресурса составляет "+str(v[len(v)-z-1]*y[z]))
    vliyan+=(v[len(v)-z-1]*y[z])
    iter+=1
print("Совместное влияние ресурсов составляет "+str(vliyan))
opt=0
for i in range(iter):
    opt+=vliyan
print("Оптимальное значение функции " + str(opt))



Максимум в стобце 1 = 14.000000035
Минимум в стобце 1 = 168.00000336000008
ограничения в столбце 1 = (-152.00000336000008;30.000000035)
Максимум в стобце 2 = inf
Минимум в стобце 2 = 12.0
ограничения в столбце 2 = (0.0;inf)
Максимум в стобце 3 = inf
Минимум в стобце 3 = 12.0
ограничения в столбце 3 = (0.0;inf)
Максимум в стобце 4 = 16.800000100800002
Минимум в стобце 4 = 11.1999999888
ограничения в столбце 4 = (4.8000000112;32.800000100800005)
Влияние 1 ресурса составляет 144.00000084
Влияние 2 ресурса составляет nan
Влияние 3 ресурса составляет nan
Влияние 4 ресурса составляет 200.00000056
Совместное влияние ресурсов составляет nan
Оптимальное значение функции nan
